/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2019-01-25 12:43:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class uploadTemplet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Workspaces/LSTEST4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LS_SQL_TEST/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/c.tld", Long.valueOf(1279244784000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl-1.2.jar", Long.valueOf(1548407344436L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,height=device-height,initial-scale=1.0\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/appCSS/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope['cssType']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/upload-template-media-query_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope['cssType']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".css?value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope['version']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".css\" /> \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"js/choosen/chosen.css\" /> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery-confirm.min.css\">\r\n");
      out.write("<script src=\"js/choosen/chosen.jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/tableHeadFixer.js\"></script> \r\n");
      out.write("<script src=\"js/jquery-confirm.min.js\" ></script>\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var resultdata=[];\r\n");
      out.write("$(document).ready( function(){\r\n");
      out.write("\t$('[data-toggle=\"tooltip\"]').tooltip(); \r\n");
      out.write("\t $(\".singleChosen\").chosen({width: \"265px\"});\r\n");
      out.write("\t$(\"#myTable\").tableHeadFixer(); \r\n");
      out.write("\t\r\n");
      out.write("\tconsole.info(\"clickedButton=\"+\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clickedButton}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"); \r\n");
      out.write("\t\r\n");
      out.write("\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clickedButton}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"==''){\r\n");
      out.write("\t$(\"#dealerTemplateDivId\").hide();\r\n");
      out.write("\t$(\"#btnback\").hide();\r\n");
      out.write("\t$(\"#DealerTable\").hide();\r\n");
      out.write("\t$(\"#btn-wrap\").hide();\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnTab\").show();\t\r\n");
      out.write("\t$(\".DownloadDiv\").show();\r\n");
      out.write("\t$(\".UploadDiv\").show();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t$(\"#btnTab\").hide();\t\r\n");
      out.write("\t$(\".DownloadDiv\").hide();\r\n");
      out.write("\t$(\".UploadDiv\").hide();\r\n");
      out.write("\t$(\"#dealerTemplateDivId\").show();\r\n");
      out.write("\t$(\"#btnback\").show();\r\n");
      out.write("\t$(\"#DealerTable\").show();\r\n");
      out.write("\t$(\".btn-wrap\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnTab\").click(function(){\r\n");
      out.write("\t$(\"#btnTab\").hide();\t\r\n");
      out.write("\t$(\".DownloadDiv\").hide();\r\n");
      out.write("\t$(\".UploadDiv\").hide();\r\n");
      out.write("\t$(\"#dealerTemplateDivId\").show();\r\n");
      out.write("\t$(\"#btnback\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnback\").click(function(){\r\n");
      out.write("\t$(\"#dealerTemplateDivId\").hide();\r\n");
      out.write("\t$(\"#DealerTable\").hide();\r\n");
      out.write("\t$(\".btn-wrap\").hide();\r\n");
      out.write("\t$(\"#btnback\").hide();\r\n");
      out.write("\t$(\"#btnTab\").show();\t\r\n");
      out.write("\t$(\".DownloadDiv\").show();\r\n");
      out.write("\t$(\".UploadDiv\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${submitFlag}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"=='true'){\r\n");
      out.write("\t\t$(\"#btnTab\").hide();\t\r\n");
      out.write("\t\t$(\".DownloadDiv\").hide();\r\n");
      out.write("\t\t$(\".UploadDiv\").hide();\r\n");
      out.write("\t\t$(\"#dealerTemplateDivId\").show();\r\n");
      out.write("\t\t$(\"#btnback\").show();\r\n");
      out.write("\t\t$(\"#DealerTable\").hide();\r\n");
      out.write("\t\t$(\".btn-wrap\").hide();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("$('#companyName').autocomplete({\r\n");
      out.write("minLength: 1,\r\n");
      out.write("source: getCompanyData,\r\n");
      out.write("select:function(event,ui){\r\n");
      out.write("var selectedCompany = $.trim(ui.item.label);\r\n");
      out.write("$.each(resultdata, function(k, v) {\r\n");
      out.write("\tif(selectedCompany===v){\r\n");
      out.write("\t$('#companyId').val(k);\t\t\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#companyNameToExport').autocomplete({\r\n");
      out.write("\tminLength: 1,\r\n");
      out.write("\tsource: getCompanyDataByCompanyName,\r\n");
      out.write("\tselect:function(event,ui){\r\n");
      out.write("\tvar selectedCompany = $.trim(ui.item.label);\r\n");
      out.write("\tvar resultVal=[];\r\n");
      out.write("\t$.each(resultdata, function(k, v) {\r\n");
      out.write("\t\tif(selectedCompany===k){\r\n");
      out.write("\t\t\tresultVal=v.split(\"~\");\r\n");
      out.write("\t\t\tif((resultVal!=null && resultVal!=undefined && resultVal!=\"undefined\") && resultVal.length==2){\r\n");
      out.write("\t\t\t\t$('#eIdToExport').val(resultVal[1]);\t\r\n");
      out.write("\t\t\t\t$('#companyIdToExport').val(resultVal[0]);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$('#eIdToExport').val(\"\");\t\r\n");
      out.write("\t\t\t\t$('#companyIdToExport').val(\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("$('#companyIdToExport').autocomplete({\r\n");
      out.write("\tminLength: 1,\r\n");
      out.write("\tsource: getCompanyDataByCompanyId,\r\n");
      out.write("\tselect:function(event,ui){\r\n");
      out.write("\tvar selectedCompany = $.trim(ui.item.label);\r\n");
      out.write("\tvar resultVal=[];\r\n");
      out.write("\t$.each(resultdata, function(k, v) {\r\n");
      out.write("\t\tif(selectedCompany===k){\r\n");
      out.write("\t\t\tresultVal=v.split(\"~\");\r\n");
      out.write("\t\t\tif((resultVal!=null && resultVal!=undefined && resultVal!=\"undefined\") && resultVal.length==2){\r\n");
      out.write("\t\t\t\t$('#eIdToExport').val(resultVal[1]);\t\r\n");
      out.write("\t\t\t\t$('#companyNameToExport').val(resultVal[0]);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$('#eIdToExport').val(\"\");\t\r\n");
      out.write("\t\t\t\t$('#companyNameToExport').val(\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("$('#companyNameToExportExtraction').autocomplete({\r\n");
      out.write("\tminLength: 1,\r\n");
      out.write("\tsource: getCompanyDataByCompanyNameForExtract,\r\n");
      out.write("\tselect:function(event,ui){\r\n");
      out.write("\tvar selectedCompany = $.trim(ui.item.label);\r\n");
      out.write("\tvar resultVal=[];\r\n");
      out.write("\t$.each(resultdata, function(k, v) {\r\n");
      out.write("\t\tif(selectedCompany===k){\r\n");
      out.write("\t\t\tresultVal=v.split(\"~\");\r\n");
      out.write("\t\t\tif((resultVal!=null && resultVal!=undefined && resultVal!=\"undefined\") && resultVal.length==2){\r\n");
      out.write("\t\t\t\t$('#eIdToExportExtraction').val(resultVal[1]);\t\r\n");
      out.write("\t\t\t\t$('#companyIdToExportExtraction').val(resultVal[0]);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$('#eIdToExportExtraction').val(\"\");\t\r\n");
      out.write("\t\t\t\t$('#companyIdToExportExtraction').val(\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("$('#companyIdToExportExtraction').autocomplete({\r\n");
      out.write("\tminLength: 1,\r\n");
      out.write("\tsource: getCompanyDataByCompanyIdForExtract,\r\n");
      out.write("\tselect:function(event,ui){\r\n");
      out.write("\tvar selectedCompany = $.trim(ui.item.label);\r\n");
      out.write("\tvar resultVal=[];\r\n");
      out.write("\t$.each(resultdata, function(k, v) {\r\n");
      out.write("\t\tif(selectedCompany===k){\r\n");
      out.write("\t\t\tresultVal=v.split(\"~\");\r\n");
      out.write("\t\t\tif((resultVal!=null && resultVal!=undefined && resultVal!=\"undefined\") && resultVal.length==2){\r\n");
      out.write("\t\t\t\t$('#eIdToExportExtraction').val(resultVal[1]);\t\r\n");
      out.write("\t\t\t\t$('#companyNameToExportExtraction').val(resultVal[0]);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$('#eIdToExportExtraction').val(\"\");\t\r\n");
      out.write("\t\t\t\t$('#companyNameToExportExtraction').val(\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function resetCompanyInfo(){\r\n");
      out.write("\t$('#companyNameToExport').val(\"\");\r\n");
      out.write("\t$('#companyIdToExport').val(\"\");\r\n");
      out.write("\t$('#eIdToExport').val(\"\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function resetCompanyInfoForExtraction(){\r\n");
      out.write("\t$('#companyNameToExportExtraction').val(\"\");\r\n");
      out.write("\t$('#companyIdToExportExtraction').val(\"\");\r\n");
      out.write("\t$('#eIdToExportExtraction').val(\"\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function resetFinanceItemFilter(){\r\n");
      out.write("\t$('#companyNameToExport').val(\"\");\r\n");
      out.write("\t$('#companyIdToExport').val(\"\");\r\n");
      out.write("\t$('#eIdToExport').val(\"\");\r\n");
      out.write("\t$('#startDateToExport').val(\"\");\r\n");
      out.write("\t$('#endDateToExport').val(\"\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function resetExtractionFilter(){\r\n");
      out.write("\t$('#companyNameToExportExtraction').val(\"\");\r\n");
      out.write("\t$('#companyIdToExportExtraction').val(\"\");\r\n");
      out.write("\t$('#eIdToExportExtraction').val(\"\");\r\n");
      out.write("\t$('#startDateToExportExtraction').val(\"\");\r\n");
      out.write("\t$('#endDateToExportExtraction').val(\"\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function setCompanyNameOnFocusOut(searchType){\r\n");
      out.write("\tvar selectedCompanyId=$(\"#companyIdToExport\").val();\r\n");
      out.write("\tvar resultVal=[];\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype: 'GET',\r\n");
      out.write("\t\turl: 'companyIdForFItems.htm',\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tcache: true,\r\n");
      out.write("\t\tdata: {companyIdToExport : $(\"#companyIdToExport\").val(),autoCompleteflag :\"N\"},\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\tif (data != null){  \r\n");
      out.write("\t\t\t\tvar resultJSON=JSON.stringify(data);\r\n");
      out.write("\t\t\t\tresultdata = $.parseJSON(resultJSON);\r\n");
      out.write("\t\t\t\t$.each(resultdata, function(k, v) {\r\n");
      out.write("\t\t\t\t\tif(selectedCompanyId==k){\r\n");
      out.write("\t\t\t\t\t\tresultVal=v.split(\"~\");\r\n");
      out.write("\t\t\t\t\t\tif((resultVal!=null && resultVal!=undefined && resultVal!=\"undefined\") && resultVal.length==2){\r\n");
      out.write("\t\t\t\t\t\t\tif(searchType == \"fITem\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#eIdToExport').val(resultVal[1]);\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#companyNameToExport').val(resultVal[0]);\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#eIdToExportExtraction').val(resultVal[1]);\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#companyNameToExportExtraction').val(resultVal[0]);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tif(searchType == \"fITem\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#eIdToExport').val(\"\");\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#companyNameToExport').val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#eIdToExportExtraction').val(\"\");\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#companyNameToExportExtraction').val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("function setCompanyIDOnFocusOut(searchType){\r\n");
      out.write("\tvar selectedCompanyName=$(\"#companyNameToExport\").val();\r\n");
      out.write("\tvar resultVal=[];\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype: 'GET',\r\n");
      out.write("\t\turl: 'companyNameForFItems.htm',\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tcache: true,\r\n");
      out.write("\t\tdata: {companyNameToExport : $(\"#companyNameToExport\").val(),autoCompleteflag :\"N\"},\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\tif (data != null){  \r\n");
      out.write("\t\t\t\tvar resultJSON=JSON.stringify(data);\r\n");
      out.write("\t\t\t\tresultdata = $.parseJSON(resultJSON);\r\n");
      out.write("\t\t\t\t$.each(resultdata, function(k, v) {\r\n");
      out.write("\t\t\t\t\tif(selectedCompanyName==k){\r\n");
      out.write("\t\t\t\t\t\tresultVal=v.split(\"~\");\r\n");
      out.write("\t\t\t\t\t\tif((resultVal!=null && resultVal!=undefined && resultVal!=\"undefined\") && resultVal.length==2){\r\n");
      out.write("\t\t\t\t\t\t\tif(searchType == \"fITem\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#eIdToExport').val(resultVal[1]);\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#companyIdToExport').val(resultVal[0]);\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#eIdToExportExtraction').val(resultVal[1]);\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#companyIdToExportExtraction').val(resultVal[0]);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tif(searchType == \"fITem\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#eIdToExport').val(\"\");\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#companyIdToExport').val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#eIdToExportExtraction').val(\"\");\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#companyIdToExportExtraction').val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function getCompanyDataByCompanyName(request, response)\r\n");
      out.write("{\r\n");
      out.write("\t$('#startDateToExport').val(\"\");\r\n");
      out.write("\t$('#endDateToExport').val(\"\");\r\n");
      out.write("\t$('#eIdToExport').val(\"\");\r\n");
      out.write("\tconsole.log($(\"#companyNameToExport\").val());\r\n");
      out.write("\tvar resultsArray=[];\r\n");
      out.write("\tconsole.info(\"in getCompanyDataByCompanyName function \");\r\n");
      out.write("\tvar resultsArray =[];\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype: 'GET',\r\n");
      out.write("\t\turl: 'companyNameForFItems.htm',\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tcache: true,\r\n");
      out.write("\t\tdata: {companyNameToExport : $(\"#companyNameToExport\").val(),autoCompleteflag :\"Y\"},\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\tif (data != null){  \r\n");
      out.write("\t\tvar resultJSON=JSON.stringify(data);\r\n");
      out.write("\t\tresultdata = $.parseJSON(resultJSON);\r\n");
      out.write("\t\t$.each(resultdata, function(k, v) {\r\n");
      out.write("\t\t   resultsArray.push(k);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tresponse(resultsArray);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getCompanyDataByCompanyId(request, response)\r\n");
      out.write("{\r\n");
      out.write("\t$('#startDateToExport').val(\"\");\r\n");
      out.write("\t$('#endDateToExport').val(\"\");\r\n");
      out.write("\t$('#eIdToExport').val(\"\");\r\n");
      out.write("\tconsole.log($(\"#companyIdToExport\").val());\r\n");
      out.write("\tvar resultsArray=[];\r\n");
      out.write("\tconsole.info(\"in getCompanyDataByCompanyId function \");\r\n");
      out.write("\tvar resultsArray =[];\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype: 'GET',\r\n");
      out.write("\t\turl: 'companyIdForFItems.htm',\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tcache: true,\r\n");
      out.write("\t\tdata: {companyIdToExport : $(\"#companyIdToExport\").val(),autoCompleteflag :\"Y\"},\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\tif (data != null){  \r\n");
      out.write("\t\tvar resultJSON=JSON.stringify(data);\r\n");
      out.write("\t\tresultdata = $.parseJSON(resultJSON);\r\n");
      out.write("\t\t$.each(resultdata, function(k, v) {\r\n");
      out.write("\t\t   resultsArray.push(k);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tresponse(resultsArray);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getCompanyDataByCompanyNameForExtract(request, response)\r\n");
      out.write("{\r\n");
      out.write("\t$('#startDateToExportExtraction').val(\"\");\r\n");
      out.write("\t$('#endDateToExportExtraction').val(\"\");\r\n");
      out.write("\t$('#eIdToExportExtraction').val(\"\");\r\n");
      out.write("\tconsole.log($(\"#companyNameToExportExtraction\").val());\r\n");
      out.write("\tvar resultsArray=[];\r\n");
      out.write("\tconsole.info(\"in getCompanyDataByCompanyNameExtraction function \");\r\n");
      out.write("\tvar resultsArray =[];\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype: 'GET',\r\n");
      out.write("\t\turl: 'companyNameForFItems.htm',\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tcache: true,\r\n");
      out.write("\t\tdata: {companyNameToExport : $(\"#companyNameToExportExtraction\").val(),autoCompleteflag :\"Y\"},\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\tif (data != null){  \r\n");
      out.write("\t\tvar resultJSON=JSON.stringify(data);\r\n");
      out.write("\t\tresultdata = $.parseJSON(resultJSON);\r\n");
      out.write("\t\t$.each(resultdata, function(k, v) {\r\n");
      out.write("\t\t   resultsArray.push(k);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tresponse(resultsArray);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getCompanyDataByCompanyIdForExtract(request, response)\r\n");
      out.write("{\r\n");
      out.write("\t$('#startDateToExportExtraction').val(\"\");\r\n");
      out.write("\t$('#endDateToExportExtraction').val(\"\");\r\n");
      out.write("\t$('#eIdToExportExtraction').val(\"\");\r\n");
      out.write("\tconsole.log($(\"#companyIdToExportExtraction\").val());\r\n");
      out.write("\tvar resultsArray=[];\r\n");
      out.write("\tconsole.info(\"in getCompanyDataByCompanyId function \");\r\n");
      out.write("\tvar resultsArray =[];\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype: 'GET',\r\n");
      out.write("\t\turl: 'companyIdForFItems.htm',\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tcache: true,\r\n");
      out.write("\t\tdata: {companyIdToExport : $(\"#companyIdToExportExtraction\").val(),autoCompleteflag :\"Y\"},\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\tif (data != null){  \r\n");
      out.write("\t\tvar resultJSON=JSON.stringify(data);\r\n");
      out.write("\t\tresultdata = $.parseJSON(resultJSON);\r\n");
      out.write("\t\t$.each(resultdata, function(k, v) {\r\n");
      out.write("\t\t   resultsArray.push(k);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tresponse(resultsArray);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function exporFItemsByFilter() {\r\n");
      out.write("\tvar startDate=$('#startDateToExport').val();\r\n");
      out.write("\tvar endDate=$('#endDateToExport').val();\r\n");
      out.write("\tvar companyIdToExport=$('#companyIdToExport').val();\r\n");
      out.write("\tvar companyNameToExport=$('#companyNameToExport').val();\r\n");
      out.write("\tvar eIdToExport=$('#eIdToExport').val();\r\n");
      out.write("\tif($.trim(startDate).length>0 ||  $.trim(endDate).length>0 || $.trim(companyIdToExport).length>0 ||  $.trim(companyNameToExport).length>0){\r\n");
      out.write("\t\tlocation.href = \"exportFinancialItemExcelByFilter.htm?startDate=\"+encodeURIComponent(startDate)+\"&endDate=\"+encodeURIComponent(endDate)+\"&companyIdToExport=\"+encodeURIComponent(companyIdToExport)+\"&companyNameToExport=\"+encodeURIComponent(companyNameToExport)+\"&eIdToExport=\"+encodeURIComponent(eIdToExport);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$.alert(\"Please provide input to download the data.\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function uploadFinancialItems() {\r\n");
      out.write("\tshowLoading();\r\n");
      out.write("\tvar myForm = new FormData();\r\n");
      out.write("\tmyForm.append(\"file\", importInputFile.files[0]);\r\n");
      out.write("\tvar filename = $(\"#importInputFile\").val();\r\n");
      out.write("\t var extension = filename.replace(/^.*\\./, '');\r\n");
      out.write("\t  if(extension.toLowerCase() === \"xlsx\"){\r\n");
      out.write("\t\t  console.log(\"SDFDSA1 \"+filename);\r\n");
      out.write("\t\t $.ajax({\r\n");
      out.write("\t\t\t    url: insertParam('importFinancialITemsExcel.htm'),\r\n");
      out.write("\t\t\t    data: myForm,\r\n");
      out.write("\t\t\t    dataType: 'text',\r\n");
      out.write("\t\t\t    processData: false,\r\n");
      out.write("\t\t\t    contentType: false,\r\n");
      out.write("\t\t\t    type: 'POST',\r\n");
      out.write("\t\t\t    cache: true,\r\n");
      out.write("\t\t\t    success: function(data){\r\n");
      out.write("\t\t\t    \tconsole.log(\"SDFDSA \"+data);\r\n");
      out.write("\t\t\t    \t$.alert(data);\r\n");
      out.write("\t\t\t    \t$(\"#importInputFile\").val(\"\");\r\n");
      out.write("\t\t\t    \thideLoading();\r\n");
      out.write("\t\t\t    \t \r\n");
      out.write("\t\t\t    },error: function(data) {\r\n");
      out.write("\t\t\t    \t$(\"#importInputFile\").val(\"\");\r\n");
      out.write("\t\t\t    \thideLoading();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t  });\r\n");
      out.write("\t }/* else{\r\n");
      out.write("\t\t $(\"#uploadErrors\").html(\"<span style='color:#008000'>Selected file type is not supporting to upload.<BR>Please select Excel file to upload.</span>\");\r\n");
      out.write("\t } */\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function exporExtractionDataByFilter() {\r\n");
      out.write("\tvar startDate=$('#startDateToExportExtraction').val();\r\n");
      out.write("\tvar endDate=$('#endDateToExportExtraction').val();\r\n");
      out.write("\tvar companyIdToExport=$('#companyIdToExportExtraction').val();\r\n");
      out.write("\tvar companyNameToExport=$('#companyNameToExportExtraction').val();\r\n");
      out.write("\tvar eIdToExport=$('#eIdToExportExtraction').val();\r\n");
      out.write("\tif($.trim(startDate).length>0 ||  $.trim(endDate).length>0 || $.trim(companyIdToExport).length>0 ||  $.trim(companyNameToExport).length>0){\r\n");
      out.write("\t\tlocation.href = \"exportPdfExtractionMetaDataFilter.htm?startDate=\"+encodeURIComponent(startDate)+\"&endDate=\"+encodeURIComponent(endDate)+\"&companyIdToExport=\"+encodeURIComponent(companyIdToExport)+\"&companyNameToExport=\"+encodeURIComponent(companyNameToExport)+\"&eIdToExport=\"+encodeURIComponent(eIdToExport);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$.alert(\"Please provide input to download the data.\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function uploadExtractionMetaData() {\r\n");
      out.write("\tshowLoading();\r\n");
      out.write("\tvar myForm = new FormData();\r\n");
      out.write("\tmyForm.append(\"file\", importExtractionInputFile.files[0]);\r\n");
      out.write("\tvar filename = $(\"#importExtractionInputFile\").val();\r\n");
      out.write("\t var extension = filename.replace(/^.*\\./, '');\r\n");
      out.write("\t  if(extension.toLowerCase() === \"xlsx\"){\r\n");
      out.write("\t\t  console.log(\"extract1 \"+filename);\r\n");
      out.write("\t\t $.ajax({\r\n");
      out.write("\t\t\t    url: insertParam('importPdfExtractionMetaDataFilter.htm'),\r\n");
      out.write("\t\t\t    data: myForm,\r\n");
      out.write("\t\t\t    dataType: 'text',\r\n");
      out.write("\t\t\t    processData: false,\r\n");
      out.write("\t\t\t    contentType: false,\r\n");
      out.write("\t\t\t    type: 'POST',\r\n");
      out.write("\t\t\t    cache: true,\r\n");
      out.write("\t\t\t    success: function(data){\r\n");
      out.write("\t\t\t    \tconsole.log(\"extract123 \"+data);\r\n");
      out.write("\t\t\t    \t$.alert(data);\r\n");
      out.write("\t\t\t    \t$(\"#importExtractionInputFile\").val(\"\");\r\n");
      out.write("\t\t\t    \thideLoading();\r\n");
      out.write("\t\t\t    \t \r\n");
      out.write("\t\t\t    },error: function(data) {\r\n");
      out.write("\t\t\t    \t$(\"#importExtractionInputFile\").val(\"\");\r\n");
      out.write("\t\t\t    \thideLoading();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t  });\r\n");
      out.write("\t }/* else{\r\n");
      out.write("\t\t $(\"#uploadErrors\").html(\"<span style='color:#008000'>Selected file type is not supporting to upload.<BR>Please select Excel file to upload.</span>\");\r\n");
      out.write("\t } */\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getCompanyData(request, response)\r\n");
      out.write("{\r\n");
      out.write("\tconsole.log($(\"#companyName\").val());\r\n");
      out.write("\tvar resultsArray=[];\r\n");
      out.write("\tconsole.info(\"in getCompanyData function \");\r\n");
      out.write("\tvar resultsArray =[];\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype: 'GET',\r\n");
      out.write("\t\turl: 'companyNameAutoComplete.htm',\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tcache: true,\r\n");
      out.write("\t\tdata: {companyName : $(\"#companyName\").val()},\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\tif (data != null){  \r\n");
      out.write("\t\tvar resultJSON=JSON.stringify(data);\r\n");
      out.write("\t\tresultdata = $.parseJSON(resultJSON);\r\n");
      out.write("\t\t$.each(resultdata, function(k, v) {\r\n");
      out.write("\t\t   resultsArray.push(v);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tresponse(resultsArray);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\tfunction searchDealerTemplateRules(){\r\n");
      out.write("\t\tvar dealerName=$('#dealerName').val();\r\n");
      out.write("\t\tif(dealerName!=''){\r\n");
      out.write("\t    document.searchDealerNameForm.submit();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$.alert(\"Please select Dealer Name\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("function generateFinancialExport() {\r\n");
      out.write("var companyId=$(\"#companyId\").val();\r\n");
      out.write("if(companyId!=''){\r\n");
      out.write("var processData = \"companyId=\"+companyId;\r\n");
      out.write("actionUrl = \"isFinancialItemExistByCompanyId.htm\";\r\n");
      out.write("successData = function(data) {\r\n");
      out.write("\t\ttry {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tresult = JSON.parse(data);\r\n");
      out.write("\t\t\tconsole.info(\"json result:\"+result);\r\n");
      out.write("\t\t\tif (result.hasOwnProperty('existFlag')) {\r\n");
      out.write("\t\t\t\t/* Here we split string by comma */\r\n");
      out.write("\t\t\t\tvar existFlag=result['existFlag'];\r\n");
      out.write("\t\t\t        if(existFlag!='Y'){\r\n");
      out.write("\t\t\t        $.alert(\"Records are not exist !\");\r\n");
      out.write("\t\t\t        }else{\r\n");
      out.write("\t\t\t        hideLoading();\r\n");
      out.write("\t\t\t        location.href = \"exportFinancialItemExcel.htm?companyId=\"+encodeURIComponent(companyId);\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\thideLoading();\r\n");
      out.write("\t\t} catch (e) {\r\n");
      out.write("\t\t\thideLoading();\r\n");
      out.write("\t\t\t$.alert(\"Error:\" + e);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t};\r\n");
      out.write("\tshowLoading();\r\n");
      out.write("\tcallAjax(processData, successData, errorData, beforeSend,\r\n");
      out.write("\t\t\tactionUrl, reqType, retDataType);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("body{overflow:auto !important}\r\n");
      out.write("</style>\t\r\n");
      out.write("\t\t\t<div class=\"container-fluid mar-top80 rmDiv\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-heading text-center\">Normalization Rules</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-body lt-panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"account\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>Download</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Click on the download link to download the blank excel template</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Enter the 'As reported labels' and 'Normalized labels' which you want to add to your Meta-data file</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"account\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Upload</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Click on the Browse button and select the template file in which you have added the 'As reported labels' and 'Normalized labels'</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Click on 'Upload' button, once the file gets uploaded to the specified destination you would receive the confirmation message for the same</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div><!--- col-md-3 -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div id=\"upload-div-new\" class=\"upload-panel\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel panel-default panel-min-ht\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading text-center\">Upload Metadata Template</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body text-center\" style=\"margin-top:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0)\"  onclick=\"setLocationHref('downloadNormalizationTemplate.htm?templateType=normRules')\">Metadata-template.xls</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 download-panel\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel panel-default panel-min-ht\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading text-center\">Download Metadata Template</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<form id=\"templateupload\" action=\"upload_template.htm\" method=\"POST\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"fileupload\" type=\"file\" name=\"fileupload\"  style=\"margin:0  auto 15px auto; display:inline\" />  </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input  type=\"button\" value=\"Upload Template\" class=\"btn btn-info start\" onClick=\"javascript:submitTemplet();\">\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t ");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f9(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function submitTemplet(){\r\n");
      out.write("\r\n");
      out.write("      var flag = 0;\r\n");
      out.write("\t  var val=$(\"#fileupload\").val();\r\n");
      out.write("\t  var ar_name = [];\r\n");
      out.write("\t  var validExtensions = new Array();\r\n");
      out.write("\t    validExtensions[0] = 'xls';\r\n");
      out.write("        validExtensions[1] = 'xlsx'; \r\n");
      out.write("        \r\n");
      out.write("\t     if(val!==\"\"){ \r\n");
      out.write("\t\t        ar_name = val.split('.');\r\n");
      out.write("\t\t          if(ar_name.length > 2){\r\n");
      out.write("\t\t  \t          $.alert(\"please select valid Xls/Xlsx\");\r\n");
      out.write("\t\t  \t         return false;\r\n");
      out.write("\t\t          } \t\r\n");
      out.write("\t       var extension = ar_name[1].toLowerCase();\r\n");
      out.write("\t\t   for (var i = 0; i < validExtensions.length; i++) {\r\n");
      out.write("\t\t          if (extension == validExtensions[i]) {\r\n");
      out.write("\t\t           flag = 1;\r\n");
      out.write("\t\t           break;\r\n");
      out.write("\t\t       }\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t        if (flag == 1) {\r\n");
      out.write("\t        \t//upload Template File \r\n");
      out.write("\t\t\t\tuploadTemplateFile();\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$.alert('Please select valid xls/xlsx');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$.alert('Please select file to upload');\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\r\n");
      out.write("\t\t\t'#startDateToExport, #endDateToExport, #startDateToExportExtraction, #endDateToExportExtraction')\r\n");
      out.write("\t\t\t.datepicker();\r\n");
      out.write("\r\n");
      out.write("\tfunction uploadTemplateFile() {\r\n");
      out.write("\t\tshowLoading();\r\n");
      out.write("\t\tvar myForm = new FormData();\r\n");
      out.write("\t\tmyForm.append(\"file\", fileupload.files[0]);\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : insertParam('upload_template.htm'),\r\n");
      out.write("\t\t\tdata : myForm,\r\n");
      out.write("\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\tprocessData : false,\r\n");
      out.write("\t\t\tcontentType : false,\r\n");
      out.write("\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\tcache: true,\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t$.alert(data);\r\n");
      out.write("\t\t\t\thideLoading();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(data) {\r\n");
      out.write("\t\t\t\t$(\"#importInputFile\").val(\"\");\r\n");
      out.write("\t\t\t\thideLoading();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/uploadTemplet.jsp(623,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.msg eq'0'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<div style=\"color:red\">Template uploaded unsuccessfully.</div>\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/jsp/uploadTemplet.jsp(626,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.msg eq '2'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<div style=\"color:red\">Template uploaded successfully. Please see the FailedRecords xls file.</div>\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/jsp/uploadTemplet.jsp(629,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.msg eq '1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<div style=\"color:red\">Template uploaded successfully.</div>\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/jsp/uploadTemplet.jsp(632,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.msg eq '3'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<div style=\"color:red\"> please select valid Xls/Xlsx.</div>\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/jsp/uploadTemplet.jsp(635,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.msg eq '4'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<div style=\"color:red\">Please select file to upload.</div>\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /WEB-INF/jsp/uploadTemplet.jsp(646,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userAccess eq '1' || userAccess eq '2'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 expo-import-panel\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading text-center\">Export/Import Financial Items</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
          out.write("\t\t\t\t\t\t\t\t    <div id=\"exportFinancialDiv\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12 mar-negi12 txt-error\">*Please provide company information/date range </div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-3 comp-name\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<label>Company Name:</label>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"companyNameToExport\" name=\"companyNameToExport\"  onblur=\"setCompanyIDOnFocusOut('fITem');\"/>\r\n");
          out.write("\t\t\t\t\t\t  \t\t\t\t\t<input type=\"hidden\" class=\"form-control\" name=\"eIdToExport\" id=\"eIdToExport\" value=\"\" />\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-3 comp-id\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<label>Company Id:</label>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"companyIdToExport\" class=\"form-control\" name=\"companyIdToExport\"  onblur=\"setCompanyNameOnFocusOut('fITem');\"/>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 str-dt\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>Start Date:</label>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"startDateToExport\" name=\"startDateToExport\"  readonly=\"readonly\" onkeyup=\"resetCompanyInfo();\" onchange=\"resetCompanyInfo();\" onfocus=\"resetCompanyInfo();\"/>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 end-dt\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>End Date:</label>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"endDateToExport\" name=\"endDateToExport\" readonly=\"readonly\" onkeyup=\"resetCompanyInfo();\" onchange=\"resetCompanyInfo();\" onfocus=\"resetCompanyInfo();\"/>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-right btn-panel\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"JavaScript:void('0');\" data-toggle=\"tooltip\" data-placement=\"top\"  title=\"Financial Item Export\" onclick=\"exporFItemsByFilter();\" id=\"exportToExcel\"><i class=\"glyphicon glyphicon-export custom-font pad5 cus-cls mar-rt5\"></i></a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"JavaScript:void('0');\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Financial Item Import\" onclick=\"$('#importInputFile').click();\" id=\"exportToExcel\"><i class=\"glyphicon glyphicon-import custom-font pad5 cus-cls mar-rt5\"></i></a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"JavaScript:resetFinanceItemFilter();\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Reset\"  id=\"resetFinanceItemFilter\"><i class=\"fa fa-undo custom-font pad5 cus-cls mar-rt5\"></i></a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<form enctype=\"multipart/form-data\" id=\"impFinanceFile\" >\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t \t<input type=\"file\" id=\"importInputFile\" name=\"importInputFile\" style=\"display: none;\" onchange=\"uploadFinancialItems();\" />\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</div><!-- row -->\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div><!-- col-md-6 -->\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\t\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /WEB-INF/jsp/uploadTemplet.jsp(700,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userAccess eq '1' || userAccess eq '2'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-md-12 expo-import-extraction-panel\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading text-center\">Export/Import Extraction Rules</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<div id=\"exportFinancialDiv\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12 mar-negi12 txt-error\">*Please provide company information/date range </div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-3 comp-name\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<label>Company Name:</label>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"companyNameToExportExtraction\" name=\"companyNameToExportExtraction\" class=\"form-control\"  onblur=\"setCompanyIDOnFocusOut('Extraction');\"/>\r\n");
          out.write("\t\t\t\t\t\t \t\t\t\t\t <input type=\"hidden\" name=\"eIdToExportExtraction\" id=\"eIdToExportExtraction\" value=\"\" class=\"form-control\" />\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-3 comp-id\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<label>Company Id:</label>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"companyIdToExportExtraction\" name=\"companyIdToExportExtraction\" class=\"form-control\"  onblur=\"setCompanyNameOnFocusOut('Extraction');\"/>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 str-dt\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>Start Date:</label>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"startDateToExportExtraction\" name=\"startDateToExportExtraction\" class=\"form-control\" readonly=\"readonly\" onkeyup=\"resetCompanyInfoForExtraction();\" onchange=\"resetCompanyInfoForExtraction();\" onfocus=\"resetCompanyInfoForExtraction();\"/>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 end-dt\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>End Date:</label>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"endDateToExportExtraction\" name=\"endDateToExportExtraction\" class=\"form-control\"  readonly=\"readonly\" onkeyup=\"resetCompanyInfoForExtraction();\" onchange=\"resetCompanyInfoForExtraction();\" onfocus=\"resetCompanyInfoForExtraction();\"/>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-right btn-panel\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"JavaScript:void('0');\" data-toggle=\"tooltip\" data-placement=\"top\"  title=\"Extraction Data Export\" onclick=\"exporExtractionDataByFilter();\" id=\"exportToExcel\"><i class=\"glyphicon glyphicon-export custom-font pad5 cus-cls mar-rt5\"></i></a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"JavaScript:void('0');\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Extraction Data Import\" onclick=\"$('#importExtractionInputFile').click();\" id=\"exportToExcel\"><i class=\"glyphicon glyphicon-import custom-font pad5 cus-cls mar-rt5\"></i></a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"JavaScript:resetExtractionFilter();\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Reset\"  id=\"resetExtractionFilter\"><i class=\"fa fa-undo custom-font pad5 cus-cls mar-rt5\"></i></a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<form enctype=\"multipart/form-data\" id=\"impFinanceFile\" >\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"file\" id=\"importExtractionInputFile\" name=\"importExtractionInputFile\" style=\"display: none;\" onchange=\"uploadExtractionMetaData();\" />\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</div><!-- row -->\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div><!-- col-md-6 -->\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f7(_jspx_th_c_005fif_005f6, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\t\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f6, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f6);
      // /WEB-INF/jsp/uploadTemplet.jsp(744,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty submitFlag}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f8(_jspx_th_c_005fif_005f7, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f7, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f7);
      // /WEB-INF/jsp/uploadTemplet.jsp(745,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${submitFlag}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
      if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<div id=\"error-div\" class=\"error-div\" style=\"margin-top:40px; background:none !important; text-align:center; font-weight:bold; border:1px solid #ccc; color:#3c763d !important\">\r\n");
          out.write("\t\t\t\t\t\t\t\t    Dealer Template Rules has been submitted successfully\r\n");
          out.write("\t\t\t\t              \t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f9 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f9.setParent(null);
      // /WEB-INF/jsp/uploadTemplet.jsp(756,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f9.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userAccess eq '1' || userAccess eq '2'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f9 = _jspx_th_c_005fif_005f9.doStartTag();
      if (_jspx_eval_c_005fif_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-md-6 download-finance-item-panel\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading text-center\">Download Financial Item Details</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<div id=\"exportFinancialDiv\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 comp-name\"><label>Company Name:</label></div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 comp-name\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"companyName\" name=\"companyName\" class=\"form-control\"/></span>\r\n");
          out.write("\t\t\t\t\t\t  \t\t\t\t<input type=\"hidden\" name=\"companyId\" id=\"companyId\" value=\"\" />\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-2\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"JavaScript:void('0');\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Financial Item Export\" onclick=\"generateFinancialExport();\" id=\"exportToExcel\"><i class=\"glyphicon glyphicon-export custom-font pad5 cus-cls mar-rt5\"></i></a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\t\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f9.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f9);
    }
    return false;
  }
}
