/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2019-01-25 12:31:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/Workspaces/LSTEST4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LS_SQL_TEST/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/c.tld", Long.valueOf(1279244784000L));
    _jspx_dependants.put("jar:file:/C:/Workspaces/LSTEST4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LS_SQL_TEST/WEB-INF/lib/spring-security-taglibs-3.1.0.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1323100496000L));
    _jspx_dependants.put("/WEB-INF/uic/jsp/include.jsp", Long.valueOf(1548407348235L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-3.1.0.RELEASE.jar", Long.valueOf(1548407338489L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl-1.2.jar", Long.valueOf(1548407344436L));
    _jspx_dependants.put("jar:file:/C:/Workspaces/LSTEST4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LS_SQL_TEST/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1279244784000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\" manifest=\"manifest.appcache\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/jquery-2.1.1.min.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/jquery-ui.min.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/jquery.sumoselect.min.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/jquery.datetimepicker.full.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/bootstrap.min.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/bootstrap-colorpicker.min.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/migrate.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/jquery-confirm.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/bootstrap-slider.min.js\" ></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/languages/jquery.validationEngine-en.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/jquery.validationEngine.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/jqueryFileDownload.js\" ></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/commonComponents.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/commonActions.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/highcharts.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/chart.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/highcharts-3d.js\" ></script>\r\n");
      out.write("<script  type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/form.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/uic/jquery-ui.min.css\" rel=\"stylesheet\" media=\"all\" />\r\n");
      out.write("<link type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/uic/sumoselect.css\" rel=\"stylesheet\" media=\"all\" />\t\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/uic/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/uic/validationEngine.jquery.css\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\"  href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/uic/template.css\"  type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<!--custom css -->\r\n");
      out.write("<link rel=\"stylesheet\"  href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/uic/common.css\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\"  href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/uic/form.css\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\"  href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/uic/tab.css\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\"  href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/uic/ui-component.css\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/uic/bootstrap-colorpicker.css\" rel=\"stylesheet\"> \r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/uic/bootstrap-slider.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/uic/jquery.datetimepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/uic/jquery-confirm.css\">\r\n");
      out.write("<!-- ------------------------------------------------------------------------------------------------ -->            \r\n");
      out.write("<style>\r\n");
      out.write(".navbar-right li {\r\n");
      out.write("\tmargin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: 'Open Sans', sans-serif;\r\n");
      out.write("\tpadding-right: 0px !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/tableHeadFixer.js\" ></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/jquery.sorttable.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/ui-component-ajax.js\" ></script>\r\n");
      out.write("<link type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/uic/uic-table.css\" rel=\"stylesheet\" media=\"all\" />\r\n");
      out.write("<script  type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/uic/form.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>LiveSpread</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width,height=device-height,initial-scale=1.0\"/>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />   \r\n");
      out.write("\t<meta http-equiv=\"Expires\" content=\"-1\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/appCSS/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope['cssType']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope['cssType']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".css?value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope['version']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/commonCSS/custom-style.css?value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope['version']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write(" \t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/commonCSS/appheader.css?value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope['version']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> \r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/jquery/smoothness/jquery-ui.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/commonCSS/welcome.css?value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope['version']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"text/css\">\r\n");
      out.write(" \t<link rel=\"stylesheet\" href=\"css/appCSS/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope['cssType']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/welcome_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope['cssType']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".css?value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope['version']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"text/css\">\r\n");
      out.write("\t<link type=\"text/css\" href=\"fonts/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link type=\"text/css\" href=\"fonts/glyphicons/css/glyphicons.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link type=\"text/css\" href=\"fonts/themify-icons/themify-icons.css\" rel=\"stylesheet\"><!-- Themify Icons -->\r\n");
      out.write("\t<script src=\"js/jquery/jquery-migrate.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/common.js?value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope['version']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/fabric.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/pdf.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/pdf.combined.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/compatibility.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/lspdfoperations.js?value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope['version']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/reports/amChart.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/reports/serial.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/reports/none.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/datepickr.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/bootstrap-multiselect.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/appjs/welcome.js?value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope['version']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t(function (global) { \r\n");
      out.write("\r\n");
      out.write("\t    if(typeof (global) === \"undefined\") {\r\n");
      out.write("\t        throw new Error(\"window is undefined\");\r\n");
      out.write("\t    }\r\n");
      out.write("\r\n");
      out.write("\t    var _hash = \"!\";\r\n");
      out.write("\t    var noBackPlease = function () {\r\n");
      out.write("\t        global.location.href += \"#\";\r\n");
      out.write("\r\n");
      out.write("\t        global.setTimeout(function () {\r\n");
      out.write("\t            global.location.href += \"!\";\r\n");
      out.write("\t        }, 50);\r\n");
      out.write("\t    };\r\n");
      out.write("\r\n");
      out.write("\t    global.onhashchange = function () {\r\n");
      out.write("\t        if (global.location.hash !== _hash) {\r\n");
      out.write("\t            global.location.hash = _hash;\r\n");
      out.write("\t        }\r\n");
      out.write("\t    };\r\n");
      out.write("\r\n");
      out.write("\t    global.onload = function () {            \r\n");
      out.write("\t        noBackPlease();        \r\n");
      out.write("\t    }\r\n");
      out.write("\r\n");
      out.write("\t})(window);\r\n");
      out.write("\twindow.location.hash=\"no-back-button\";\r\n");
      out.write("\twindow.location.hash=\"Again-No-back-button\";//again because google chrome don't insert first hash into history\r\n");
      out.write("\twindow.onhashchange=function(){window.location.hash=\"no-back-button\";}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<script>\r\n");
      out.write("var checkBoxArray=new Array();\r\n");
      out.write("\t$(document).ready( function() {\r\n");
      out.write("\t\t$(\"#btnClose, #btnBatch\").click(function() {\r\n");
      out.write("\t\t$('input[type=text]').each(function() {\r\n");
      out.write("\t\t$(this).val('');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tshowMenuHeader();\t\r\n");
      out.write("\t$(\"#workQueueSearchElementsContainer\").hide();\r\n");
      out.write("\t$(\".lll\").click(function() {$(\"#uic_search_workQueue\").show().appendTo(\"#hello\");$( \"input\" ).autocomplete({\r\n");
      out.write("\t\t  appendTo: \"#hello\"\r\n");
      out.write("\t});});\r\n");
      out.write("\t$('#closewq').click(function() { $('#uic_search_workQueue').hide(); });\r\n");
      out.write("\t $('div#uic_SearchRefreshDiv_workQueue button').click( function() {$('#uic_search_workQueue').hide();  $('#myModal').modal('hide'); });\r\n");
      out.write("\t $('#uic_DynamicResetButton_workQueue').click( function() {\r\n");
      out.write("\t\t jQuery(\"#includeSelectAllOption\").find(\"option\").removeAttr(\"selected\");\r\n");
      out.write("\t }); \r\n");
      out.write("\t$('#dynamicSearchworkQueue select').multiselect({\r\n");
      out.write("\t\tincludeSelectAllOption: true,\r\n");
      out.write("      \tenableCaseInsensitiveFiltering: true,\r\n");
      out.write("      \tbuttonWidth: '170px'\r\n");
      out.write("\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t  jQuery(function(){\r\n");
      out.write("\t      jQuery('.multiselect-clear-filter').click();\r\n");
      out.write("\t    });\r\n");
      out.write("\t  \r\n");
      out.write("\t  $(\"#uic_DynamicResetButton_workQueue\").click(function () {\r\n");
      out.write("\t\t    $('option', $('#dynamicSearchworkQueue select')).each(function (element) {\r\n");
      out.write("\t\t        $(this).removeAttr('selected').prop('selected', false);\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t    $('#dynamicSearchworkQueue select').multiselect('refresh');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t  \r\n");
      out.write("\t  /* $(\"#dynamicSearchworkQueueTable .multiselect-container li:nth-child(3)\").remove();\r\n");
      out.write("\t  $(\"#dynamicSearchworkQueueTable .multiselect-container li:nth-child(3)\").attr('checked', false); */\t  \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".form-control {height:28px !important;}\r\n");
      out.write(".ui-autocomplete{z-index:99999}\r\n");
      out.write(".modal-backdrop {display: none;}\r\n");
      out.write(".modal {background: rgba(0,0,0,0.5);}\r\n");
      out.write(".table.uic_dynamictable > tbody > tr:nth-child(even) > td {background:#ffffff !important; border-right:1px solid #ccc !important; border-top:1px solid #ccc !important; }\r\n");
      out.write(".table.uic_dynamictable > tbody > tr:nth-child(odd) > td {background:#f4f4f4 !important; border-right:1px solid #ccc !important; border-top:1px solid #ccc !important;}\r\n");
      out.write("select {font-size: 11px; font-family:\"Helvetica Neue\",Helvetica,Arial,sans-serif; width:100%; height:27px; border: solid 1px #ccc; height: 30px; padding:0px 6px; background-color: #fff; -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075); box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075); -webkit-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s; transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;}   \r\n");
      out.write("/* select:focus {outline:none;} */\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/appheader.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("pageNo", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("1", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("<header style=\"z-index:9999 !important\">\r\n");
      out.write("<div class=\"header-wpr main-doc-width main_min_width\">\r\n");
      out.write("\t<div style=\"width:100%; margin:0px;\">\r\n");
      out.write("\t<div class=\"logo_wpr\"><a href=\"javascript:void(0)\" onclick=\"setLocationHref('welcome.htm')\" ></a></div>\r\n");
      out.write("\t<div style=\"float:left; display:none\" class=\"bdr-right-gray\"><h3 class=\"financial\" style=\"\">Financial Spreading</h3></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<table align=\"right\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"last-logged-since pull-left\">Last Logged In<span id=\"counter1\" style=\"color:#f04b5d\">&nbsp;&nbsp;");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("</span></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"logged-since pull-left\">Logged In Since &nbsp;&nbsp;<span id=\"counter\" style=\"color:#f04b5d\"></span></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown pull-left\" style=\"padding:39px 12px 0 0\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0)\"  class=\"dropdown-toggle welcome-txt custom-toggle\" type=\"button\"  data-toggle=\"dropdown\">Welcome ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.login}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <span class=\"caret-custom\"></span></a>\r\n");
      out.write("\t\t\t\t\t    <ul class=\"dropdown-menu\" role=\"menu\" style=\"margin-top:5px !important\">\r\n");
      out.write("\t\t\t\t\t      <li><a href=\"javascript:void(0)\" onclick=\"setLocationHref('changePasswordPage.htm','workQueueLink')\">Change Password</a></li>\r\n");
      out.write("\t \t\t\t  \t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t      <li><a href=\"javascript:void(0)\" onclick=\"setLocationHref('logout.htm')\" style=\"border-bottom:0px !important\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t    </ul>\r\n");
      out.write("  \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"circle\"><span class=\"glyphicon glyphicon-user user-icon\"></span></div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t<div class=\"container-fluid uicTableDiv\" style=\"margin-top:100px\">\r\n");
      out.write("\t  \t<div class=\"row\">\r\n");
      out.write("\t  \t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t  \t\t\t<div id=\"search-panel\" class=\"pull-right\">\r\n");
      out.write("\t  \t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t  \t\t\t<button type=\"button\" class=\"btn-info-green lll\" data-toggle=\"modal\" data-target=\"#myModal\"><span class=\"glyphicon glyphicon-search\" style=\"padding:0 5px 0 5px\"></span>Custom Search</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn-info-green 111\" onclick=\"resetData('workQueue','getTablePage.htm');\">Reset</button>\r\n");
      out.write("\t  \t\t\t</div>\r\n");
      out.write("\t  \t\t</div>\r\n");
      out.write("\t  \t</div>\r\n");
      out.write("\t  \t<div id=\"uic_Table\" class=\"mar-top10\"></div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"mainPageDiv\">\r\n");
      out.write("\t\t\t<div class=\"row batch-process-wrapper\">\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t\t<div id=\"overallPortfolioDiv\" class=\"content_wpr main-doc-width main_min_width mar-top20 lsContentDiv\" style=\"display:none;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"myPortfolioDiv\" class=\"content_wpr main-doc-width main_min_width mar-top20 lsContentDiv\" style=\"display:none;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"uploadDocumentDiv\" class=\"content_wpr main-doc-width main_min_width mar-top20 lsContentDiv\" style=\"display:none;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"normalizationTemplateDiv\" class=\"content_wpr main-doc-width main_min_width mar-top20 lsContentDiv\" style=\"display:none;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"normalizationRulesDiv\" class=\"content_wpr main-doc-width main_min_width mar-top20 lsContentDiv\" style=\"display:none;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"reportsDiv\" class=\"content_wpr main-doc-width main_min_width mar-top20 lsContentDiv\" style=\"display:none;\" >\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"rulesManagementDiv\" class=\"content_wpr main-doc-width main_min_width mar-top20 lsContentDiv\" style=\"display:none;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"normalizationDiv\" class=\"content_wpr main-doc-width main_min_width mar-top20 lsContentDiv\" style=\"display:none;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"qaCheckListDiv\" class=\"content_wpr main-doc-width main_min_width mar-top20 lsContentDiv\" style=\"display:none;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"normalizedViewDiv\" class=\"content_wpr main-doc-width main_min_width mar-top20 lsContentDiv\" style=\"display:none;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<div class=\"footer_wpr main-doc-width main_min_width\"> ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" id=\"userId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${USERID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"userAccess\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${USERACCESS}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"userIdDec\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userIdDec}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"userGroupIdDec\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userGroupIdDec}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"tableName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tableName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"creationTime\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.session.creationTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"dealerNameSearch\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${delearName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"bachProcessFlag\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bachProcessFlag}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"goldenSetGroup\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goldenSetGroup}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"htmlShow\" class=\"modal fade\" role=\"dialog\" style=\"display:none;\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" id=\"htmlPopUp\">&times;</button>\r\n");
      out.write("        <h4 class=\"modal-title\">LiveSpread</h4>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <div id=\"htmlViewer\" class=\"html-viewer\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"pdfshow\" class=\"modal fade pdf-show\" role=\"dialog\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" id=\"PDFPopUp\">&times;</button>\r\n");
      out.write("        <h4 class=\"modal-title\">LiveSpread</h4>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <div id=\"viewer1\"> </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("  <div id=\"batchAssociationId\" class=\"modal fade pp\" role=\"dialog\" style=\"margin-top: 5%;\">\r\n");
      out.write("\t\t  <div class=\"modal-dialog\" style=\"width:29%\">\r\n");
      out.write("\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t      <div class=\"modal-header\">\r\n");
      out.write("\t\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" id=\"btnClose\">&times;</button>\r\n");
      out.write("\t\t        <h3 class=\"modal-title\">Batch Processing</h3>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      <div class=\"modal-body\" style=\"padding:20px 48px 20px 10px\">\r\n");
      out.write("\t\t      <div class=\"col-md-10\">\r\n");
      out.write("\t\t      \t<div class=\"pull-left\"><label>Batch Id:</label></div>\r\n");
      out.write("\t\t      \t<div class=\"pull-left mar-lt10\"><input type=\"text\" class=\"form-control\" autocomplete=\"off\" id=\"transactionId\"  onkeyup=\"setAutoCompleteList();\" style=\"z-index:99999 !important\"/></div>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn-info-green\" style=\"height:28px; padding:0 8px 0 8px !important\" id=\"batchId\" onclick=\"submitBatchId()\" >Submit</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t  <div id=\"myModal\" class=\"modal fade pp\" role=\"dialog\" style=\"margin-top:65px;\">\r\n");
      out.write("\t\t  <div class=\"modal-dialog modal-lg wdt83-perc\">\r\n");
      out.write("\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t      <div class=\"modal-header\">\r\n");
      out.write("\t\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" style=\"display:block !important\">&times;</button>\r\n");
      out.write("\t\t        <h4 class=\"modal-title\">Search</h4>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t        <div id=\"hello\"></div>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"loadinglayer\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/jsp/welcome.jsp(137,114) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setType("both");
      // /WEB-INF/jsp/welcome.jsp(137,114) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lastTime}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/welcome.jsp(143,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userAccess eq 1 || user.userAccess eq 2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t              \t\t\t\t<li><a href=\"javascript:void(0)\" onclick=\"calShowAdminPanal('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userGroupId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("');\">Admin Panel</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/jsp/welcome.jsp(163,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bachProcessFlag eq 'Y'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t  \t\t   \t<button type=\"button\" class=\"btn-info-green\" id=\"btnBatch\" data-toggle=\"modal\" data-target=\"#batchAssociationId\"><span class=\"fa fa-database\" style=\"padding:0 5px 0 5px\"></span>Batch Association</button>\r\n");
          out.write("\t\t  \t\t    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    }
    return false;
  }
}
